# Generated by Django 3.2.5 on 2021-09-20 14:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_account_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='answers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=1000), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='test',
            name='questions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=1000), default=list, size=None),
        ),
    ]
