# Generated by Django 3.2.5 on 2021-09-20 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210920_1603'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
