# Generated by Django 3.2.5 on 2021-09-20 17:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answers', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=None)),
                ('asked_by', models.CharField(max_length=50)),
                ('answered', models.BooleanField(default=False)),
                ('answered_by', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['-question'],
            },
        ),
    ]
