# Generated by Django 3.2.7 on 2021-09-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert_support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('question_text', models.TextField()),
                ('question_file', models.ImageField(blank=True, upload_to='expert_questions')),
                ('user_email', models.EmailField(max_length=254)),
                ('replier_name', models.CharField(max_length=30)),
                ('answered', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-category'],
            },
        ),
    ]
