# Generated by Django 3.2.5 on 2021-09-20 17:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), blank=True, size=None),
        ),
    ]
