# Generated by Django 3.2.5 on 2021-09-20 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_question_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='created_by',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app.account'),
            preserve_default=False,
        ),
    ]
