# Generated by Django 3.2.5 on 2021-09-20 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_course_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='materials',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.materials'),
        ),
    ]
