# Generated by Django 3.2.5 on 2021-09-21 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_expert_support'),
        ('app', '0011_alter_course_materials'),
    ]

    operations = [
    ]
